export default {
  TOGGLE_FILTER_BRAND: 'TOGGLE_FILTER_BRAND',
  SET_FILTER_PRICE: 'SET_FILTER_PRICE',
  TOGGLE_FILTER_COLLECTION: 'TOGGLE_FILTER_COLLECTION',
  SET_SORTING: 'SET_SORTING',
  RESET_FILTER_SORTING: 'RESET_FILTER_SORTING',
};
